"use client";
import { WithSubnavigation } from "@/components/navigation";
import React from "react";
import CardGames from "@/components/CardGames";
import SingGames from "@/components/SingGames";
import OwnGameCards from "@/components/OwnGameCards";
import { useGameType } from "@/hooks/useGameType";
import Footer from "@/components/Footer";
import { ChakraProvider, CSSReset } from "@chakra-ui/react";
import theme from "@/theme/theme";
import type { Metadata } from "next";
import { useTranslations } from "next-intl";

export let metadata: Metadata = {
  title: "WWWWWWWWWWWWWWWW",
  description: "Generated by create next app",
};

export default function Pages({ params }: any) {
  const game = useGameType(params);

  const t = useTranslations("Index");
  metadata = { title: t('pageName'), description: " AAAOOOOOO" };
  return (
    <>
      <ChakraProvider theme={theme}>
        <WithSubnavigation locale={params.locale} />
        {game.layoutCard === 1 && (
          <CardGames
            title={game.selectedGame.name}
            description={game.selectedGame.desc}
            gameType={game.selectedGame.cardDesc}
            lang={params.locale}
          />
        )}
        {game.layoutCard === 2 && (
          <SingGames
            title={game.horoscope.name}
            description={game.horoscope.desc}
            currentDate={game.currentDate}
            section={game.horoscope.section}
          />
        )}
        {game.layoutCard === 3 && <OwnGameCards />}
        <Footer />
      </ChakraProvider>
    </>
  );
}
