import { NextIntlClientProvider, useMessages } from "next-intl";
import { ChakraProvider, CSSReset } from "@chakra-ui/react";
import type { Metadata } from "next";
import { useTranslations } from "next-intl";

export let metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function LocaleLayout({
  children,
  params: { locale },
}: {
  children: React.ReactNode;
  params: { locale: string };
}) {
  const messages = useMessages();

  const t = useTranslations("Index");
  metadata = { title: t('pageName'), description: " AAAOOOOOO" };

  return (
    <html lang={locale}>
      <body>
        <NextIntlClientProvider locale={locale} messages={messages}>
          {children}
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
