"use client";
import React from "react";
import { useTranslations } from "next-intl";
import { WithSubnavigation } from "@/components/navigation";
import { ChakraProvider, CSSReset } from "@chakra-ui/react";
import theme from "@/theme/theme";
import type { Metadata } from "next";
import GameTypesView from "@/components/GameTypesView";
import SingTypeView from "@/components/SingTypeView";
import Banner from '@/components/Banner'

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function page({ params }: any) {
  const t = useTranslations("Index");
  const locale = params?.locale;
  return (
    <>
      <ChakraProvider theme={theme}>
        <WithSubnavigation locale={locale} />
        <Banner/>
        <GameTypesView locale={locale} />
        <SingTypeView locale={locale} />
      </ChakraProvider>
    </>
  );
}
